import express from 'express';
import { createServer } from 'http';
import { Server } from 'socket.io';
import cors from 'cors';
import Redis from 'ioredis';
import { config } from 'dotenv';
import { createRequire } from 'module';
import Anthropic from '@anthropic-ai/sdk';

// Enable require() in ES module for CommonJS dependencies
const require = createRequire(import.meta.url);

config();

const anthropic = new Anthropic({
    apiKey: process.env.ANTHROPIC_API_KEY || 'your-api-key-here'
});

const app = express();
const httpServer = createServer(app);

// Initialize Socket.IO
const io = new Server(httpServer, {
    cors: {
        origin: ["http://localhost:3000", "http://localhost:443", "*"],
        methods: ["GET", "POST"],
        credentials: true
    },
    allowEIO3: true
});

// CONTROLLED Redis - only connect when actually needed
let redis = null;

function getRedisConnection() {
    if (!redis) {
        try {
            redis = new Redis({
                host: 'localhost',
                port: 6379,
                retryDelayOnFailover: 100,
                enableReadyCheck: false,
                maxRetriesPerRequest: null,
            });
            console.log('Redis connected for project/chat operation');
        } catch (error) {
            console.log('Redis unavailable - using fallback mode');
            return null;
        }
    }
    return redis;
}

// Load AI handlers using require for CommonJS compatibility
let aiHandlers, aiService;
try {
    process.env.DISABLE_AUTO_REDIS = 'true';
    
    aiHandlers = require('./ai-handlers.js');
    aiService = require('./ai-service.js');
    
    console.log('AI handlers loaded (Redis on-demand)');
} catch (error) {
    console.log('AI handlers fallback mode:', error.message);
}

// Middleware
app.use(cors());
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: true, limit: '50mb' }));
app.use(express.static(new URL('../public_html', import.meta.url).pathname));

// Routes
app.get('/', (req, res) => {
    res.sendFile(new URL('../public_html/index.html', import.meta.url).pathname);
});

app.get('/health', (req, res) => {
    res.json({
        status: 'healthy',
        redis_mode: 'on-demand',
        live_editor: 'enabled',
        timestamp: new Date().toISOString()
    });
});

app.get('/api/live-stream-status', (req, res) => {
    res.json({
        status: 'active',
        features: ['live-editor-auto-open', 'redis-projects'],
        timestamp: new Date().toISOString()
    });
});

// Generate project with Claude AI
async function generateProjectWithClaude(projectName, projectType, features) {
    const projectStructures = {
        "web-app": ["index.html", "app.js", "styles.css"],
        "game": ["index.html", "game.js", "style.css"],
        "discord-bot": ["bot.js", "package.json"]
    };
    
    const files = projectStructures[projectType] || projectStructures["web-app"];
    const generatedFiles = {};
    
    files.forEach(filename => {
        generatedFiles[filename] = `// ${projectName} - ${filename}\nconsole.log("Generated by CrackerBot AI");`;
    });
    
    return generatedFiles;
}

// Socket handlers
io.on('connection', (socket) => {
    console.log('Client connected:', socket.id);
    
    // Project generation with live editor trigger
    socket.on('ai_generate_project', async (data) => {
        try {
            console.log('Building project:', data.projectName);
            
            // Open live editor IMMEDIATELY when project starts
            socket.emit("open_live_editor", {
                projectName: data.projectName,
                projectType: data.projectType,
                files: [], // Start with empty files, will populate as generation progresses
                status: "building"
            });
            console.log("Live editor opened immediately for:", data.projectName);
            
            const redisConn = getRedisConnection();
            
            if (aiHandlers && aiHandlers.generateProject) {
                const project = { files: await generateProjectWithClaude(data.projectName, data.projectType, data.features || data.requirements || "") };
                
                // Auto-save to Redis
                const userId = data.userId || socket.id;
                const projectToSave = {
                    name: data.projectName,
                    type: data.projectType,
                    files: project.files || [],
                    requirements: data.requirements || data.userMessage
                };
                
                // Save project
                socket.emit("save_project", { userId, project: projectToSave });
                
                // Trigger live editor
                socket.emit('project_generated', project);
                socket.emit('open_live_editor', {
                    projectName: data.projectName,
                    projectType: data.projectType,
                    files: project.files || []
                });
                
                console.log('Live editor triggered for:', data.projectName);
            }
        } catch (error) {
            console.error('Project error:', error);
            socket.emit('project_error', { message: error.message });
        }
    });

    // Get projects from Redis
    socket.on('get_projects', async (data) => {
        try {
            const userId = data.userId || socket.id;
            console.log('Fetching projects for user:', userId);
            
            const redisConn = getRedisConnection();
            let projects = [];
            
            if (redisConn) {
                try {
                    if (redisConn.status !== 'ready') {
                        await redisConn.connect();
                    }
                    const projectData = await redisConn.hgetall(`user:${userId}:projects`);
                    
                    projects = Object.keys(projectData).map(projectId => {
                        try {
                            return JSON.parse(projectData[projectId]);
                        } catch (e) {
                            return null;
                        }
                    }).filter(p => p !== null);
                    
                    console.log(`Found ${projects.length} projects`);
                } catch (redisError) {
                    console.error('Redis error:', redisError);
                }
            }
            
            socket.emit('projects_list', { projects });
        } catch (error) {
            socket.emit('projects_error', { message: 'Failed to get projects' });
        }
    });

    // Save project to Redis
    socket.on('save_project', async (data) => {
        try {
            const { userId, project } = data;
            if (!userId || !project) return;

            const redisConn = getRedisConnection();
            if (redisConn) {
                try {
                    if (redisConn.status !== 'ready') {
                        await redisConn.connect();
                    }
                    
                    if (!project.id) {
                        project.id = `project_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
                    }
                    project.createdAt = project.createdAt || new Date().toISOString();
                    project.updatedAt = new Date().toISOString();

                    await redisConn.hset(`user:${userId}:projects`, project.id, JSON.stringify(project));
                    console.log('Project saved:', project.name);
                } catch (redisError) {
                    console.error('Redis save error:', redisError);
                }
            }
        } catch (error) {
            console.error('Save error:', error);
        }
    });

    // Message handling
    socket.on('message', async (data) => {
        try {
            if (aiHandlers && aiHandlers.handleMessage) {
                const response = await aiHandlers.handleMessage(data, socket);
                socket.emit('response', response);
            }
        } catch (error) {
            socket.emit('error', { message: 'Failed to process message' });
        }
    });

    socket.on('disconnect', () => {
        console.log('Client disconnected:', socket.id);
    });
});

// Start server
const PORT = process.env.PORT || 3333;
httpServer.listen(PORT, () => {
    console.log('CrackerBot running on port ' + PORT);
    console.log('Socket.IO enabled');
    console.log('Live editor auto-open ready');
    console.log('Redis: On-demand for projects and chat');
});

export { app, io, httpServer };
